version: '2'
services:
  nodemysql:
    image: "mysql"
    command: mysqld --character-set-server=utf8 
    container_name: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - datastore:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

  nodeapp:
    build: ./node
    container_name: "usernode"
    ports:
      - "3000:3000"
    links:
      - nodemysql
    tty: true

volumes:
  datastore:
    driver_opts:
      type: none
      device: /var/opt/mysql
      o: bind
